
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        location / {
                proxy_pass http://client:3000/;
            }
            location /server/ {
                proxy_pass http://server:8080/;
            }
        location /jenkins/ {
            proxy_pass http://jenkins:8080;
            proxy_read_timeout  90;
            proxy_set_header X-Forwarded-Host $host:$server_port;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
